### ISSUE TITLE
reference not found when running soft

### ISSUE THREAD

**Issue by maxall41** [charmbracelet/soft-serve#103]
I think I accidentally screwed up my config file and now I get:
```
reference not found
```
when running `soft`
Does anybody know where the config file is stored locally on the server so I can delete it and start again?

**Comment by shadowrylander** [comment]
@maxall41 How did you resolve this? I'm currently getting the same message.

**Comment by maxall41** [comment]
Yeah i just ran `soft` in a different directory

**Comment by shadowrylander** [comment]
Huh... I did it by removing `~/.repos`, since I had just started...
