### ISSUE TITLE
repository does not exist when SOFT_SERVE_REPO_PATH is used on a mounted drive

### ISSUE THREAD

**Issue by pythonian23** [charmbracelet/soft-serve#108]
I am running Soft Serve built from source on a Raspberry Pi. I am attempting to set SOFT_SERVE_REPO_PATH to a difderent folder which is a mounted USB drive. When I run `soft`, I get an error: `repository does not exist`. It appears to still work when run on a regular folder. Also, the user I'm running `soft` from has access to the mounted folder.

**Comment by mitosch** [comment]
I had a similar problem and it was caused by a directory which wasn't a git repository.

It can be reproduced by a fresh REPO_PATH, creating an empty directory:

```
mkdir test
```

Then the following message appears:

```
repository does not exist
```

Solution:
Check for non-git directories.
