### ISSUE TITLE
Doesn't seem to work correctly on Windows...

### ISSUE THREAD

**Issue by naikrovek** [charmbracelet/soft-serve#115]
If I run this on Windows, (installing via `go install` as shown in the README) then using the Windows command line git client fails with an unexpected protocol error.  

```
git clone ssh://localhost:23231/config
Cloning into 'config'...
fatal: protocol error: unexpected 'something went wrong'
```

Hosting soft-serve on Windows and accessing the TUI works fine for both Linux and Windows SSH clients.

Hosting soft-serve on Windows and *cloning* using git clients on both Linux and Windows fails with the above error.

Hosting soft-serve on Linux and using the TUI from Windows SSH and git clients works fine.

Hosting soft-serve on Linux and using the SSH protocol to clone on Windows and Linux both work fine.

I can't imagine that this will be a high priority, but I felt it worthy of an issue, because it is an issue.  I don't know if it's soft-serve's issue, but it is an issue.

**Comment by bashbunni** [comment]
I'll try this on my Windows PC

**Comment by naikrovek** [comment]
third to last paragraph of my opening comment... reading that now seems wrong.  Windows on Windows is what doesn't work.

I *think* I meant to say that hosting on Windows and using git from Linux works fine.

I'm not in a position to verify what I wrote right, so please make sure I'm correct about all those things.

**Comment by aymanbagabas** [comment]
Fix will be part of next release :)
