### ISSUE TITLE
Implement syscall.Setgid/syscall.Setuid

### ISSUE THREAD

**Issue by mrusme** [charmbracelet/soft-serve#116]
One thing that has stopped me from running soft-serve is the fact that it doesn't support binding to port 22 and then dropping the root privileges required to do so, from what I found. Please correct me if I might have overlooked something in the documentation.

It would be nice if there was a way to make soft-serve start as root, open the port and then drop to a different user (e.g. git) in order to run the actual service.

**Comment by bashbunni** [comment]
Hey! I'd love to learn more about this. Do you know if this has been done with other projects using the `crypto/ssh` package? I'm thinking that's where I might want to start looking. If you wouldn't mind sharing any examples of other go projects that do this it would be great to take a look and share with the team

**Comment by bashbunni** [comment]
lol I totally missed the whole syscall part of the title 😂

**Comment by mrusme** [comment]
@bashbunni check [this issue](https://github.com/golang/go/issues/1435#issuecomment-890325319=) for some examples on the `syscall.Setgid/.Setuid` topic. It *seems* as if this could be done in Go, however, what I haven't validated yet is whether this implementation would work on e.g. OpenBSD as well (where I tried to run soft-serve in first place).

**Comment by aymanbagabas** [comment]
Hi @mrusme this is very doable with the current version of soft-serve. I've created a PR to add an example of doing so, could you please try [non-root/main.go](https://github.com/charmbracelet/soft-serve/blob/setuid/examples/non-root/main.go)
