### ISSUE TITLE
Allow for groups of repos

### ISSUE THREAD

**Issue by Farzat07** [charmbracelet/soft-serve#120]
Basically: directories. Grouping repos into directories helps in organisation. Example repos:

ssh://git.example.soft/bla1
ssh://git.example.soft/group1/bla2
ssh://git.example.soft/group1/bla3
ssh://git.example.soft/group1/subgroup1/bla4
ssh://git.example.soft/group1/subgroup1/bla5

**Comment by bashbunni** [comment]
Hey @Farzat07, are you be hoping for directory names to be included in the repo name so they would be shown as you listed above? If so, you can rename the repos in your config file by changing the repo `Name` field. Let me know if that's along the lines of what you're looking for

**Comment by Farzat07** [comment]
I don't think that would help in navigation right? Let's say for example I have a bunch of vim plugins I maintain once in a while. I don't want to have to scroll through all of them to get to my other repos.

**Comment by Farzat07** [comment]
Yes exactly

Nested ones would also be nice

**Comment by aymanbagabas** [comment]
Hi @agarsev, this will be part of the next release https://github.com/charmbracelet/soft-serve/pull/242
