### ISSUE TITLE
systemd ignoring SOFT_SERVE_HOST but all env vars respected when binary launched with `soft`

### ISSUE THREAD

**Issue by mmar80** [charmbracelet/soft-serve#122]
Issue: The SOFT_SERVE_HOST environment variable is not being respected when `soft` is launched with systemd, causing the git clone address to read localhost instead of SOFT_SERVE_HOST in the TUI. However, when running `soft` with the service disabled in systemctl and all the same environment variables set, the git clone address will show the correct SOFT_SERVE_HOST value.

Steps to reproduce (this was done on a fresh VM running Debian 11): 

1) Set environment variables in /etc/environment:
```
SOFT_SERVE_PORT="23231"
SOFT_SERVE_BIND_ADDRESS="0.0.0.0"
SOFT_SERVE_KEY_PATH="/home/ops/.ssh/soft_serve_server_ed25519"
SOFT_SERVE_REPO_PATH="/home/ops/.repos"
SOFT_SERVE_INITIAL_ADMIN_KEY="/home/ops/.ssh/id_ed25519.pub"
SOFT_SERVE_HOST="vcs.hazyville.net"
```
2) install git, soft serve
3) launch with `soft` and ssh to the TUI

Note the git clone address correctly reflects the SOFT_SERVE_HOST.

4) create unit file at /etc/systemd/system/soft.service, enable correct perms, with the following content:
```
[Unit]
Description=hazyville.net softserve instance
After=network.target

[Service]
Type=simple
Restart=always
RestartSec=1
ExecStart=/usr/bin/soft soft


[Install]
WantedBy=multi-user.target
```

5) enable soft.service in systemctl and restart the host
6) ssh into soft TUI and note the git clone address is now using localhost

7) Stuff I tried that didn't work:

- added this line in the `[Service]` stanza:
```
PassEnvironment=SOFT_SERVE_HOST
```
- added the env vars into the user ~/.profile as exports
- adding a wait timer to the service to ensure all vars loaded before service
- ssh from directly on the soft host and from remotes (all had same issue if soft had been launched with systemd)

8) Disabling the service in systemctl and relaunching with `soft` with no changes to the env vars will result in correct SOFT_SERVE_HOST in the TUI.

**Comment by aymanbagabas** [comment]
Hi @mmar80! The hostname in the TUI can be configured through the [config repository](https://github.com/charmbracelet/soft-serve#configuration). `SOFT_SERVE_HOST` is only used when you run the server for the first time to create the default config repository. I hope this fixes your issue.

**Comment by mmar80** [comment]
Sadly no change, but it is clear the SOFT_SERVE_HOST var is being passed into the execution environment at least:

```
ops@vcs:~$ sudo systemctl status soft.service
● soft.service - hazyville.net softserve instance
     Loaded: loaded (/etc/systemd/system/soft.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-06-13 13:08:24 CDT; 30min ago
   Main PID: 387 (soft)
      Tasks: 6 (limit: 9510)
     Memory: 32.7M
        CPU: 78ms
     CGroup: /system.slice/soft.service
             └─387 /usr/bin/soft soft vcs.hazyville.net

Jun 13 13:08:24 vcs systemd[1]: Started hazyville.net softserve instance.
Jun 13 13:08:24 vcs soft[387]: 2022/06/13 13:08:24 Starting SSH server on :23231
Jun 13 13:16:01 vcs soft[387]: 2022/06/13 13:16:01 ops connect 127.0.0.1:34514 true [] xterm-256color 111 24
Jun 13 13:16:01 vcs soft[387]: 2022/06/13 13:16:01 127.0.0.1:34514 disconnect 635.901µs
ops@vcs:~$ sudo cat /etc/systemd/system/soft.service
[Unit]
Description=hazyville.net softserve instance
After=network.target

[Service]
Type=simple
Restart=always
RestartSec=1
Environment="SOFT_SERVE_HOST=vcs.hazyville.net"
ExecStart=/usr/bin/soft soft $SOFT_SERVE_HOST


[Install]
WantedBy=multi-user.target
```

What are the recommended permissions on the config directory? Are there any other settings I can add into the config that might help test whether the config is being read correctly on load, if that is where the host name is being pulled from into the TUI?

**Comment by aymanbagabas** [comment]
@mmar80 you probably want your `soft.service` to look like this:

```conf
[Unit]
Description=hazyville.net softserve instance
After=network.target

[Service]
Type=simple
Restart=always
RestartSec=1
Environment=SOFT_SERVE_PORT="23231"
Environment=SOFT_SERVE_BIND_ADDRESS="0.0.0.0"
Environment=SOFT_SERVE_KEY_PATH="/home/ops/.ssh/soft_serve_server_ed25519"
Environment=SOFT_SERVE_REPO_PATH="/home/ops/.repos"
Environment=SOFT_SERVE_INITIAL_ADMIN_KEY="/home/ops/.ssh/id_ed25519.pub"
Environment=SOFT_SERVE_HOST="vcs.hazyville.net"
ExecStart=/usr/bin/soft


[Install]
WantedBy=multi-user.target
```

Soft Serve will use `SOFT_SERVE_REPO_PATH` to store the bare git repositories including the config repository. After you start this service, make sure that `config.yaml` has the correct host and port that you want to display in the TUI.

```
git clone ssh://localhost:23231/config
cd config
vim config.yaml # make your changes
git add config.yaml
git commit -m 'update hostname'
git push origin master
```

**Comment by mmar80** [comment]
Passing the environment variables as you suggested resolved the problem. Thanks for the help!
