### ISSUE TITLE
Can't push to remote soft-serve

### ISSUE THREAD

**Issue by donuts-are-good** [charmbracelet/soft-serve#136]
I am able to SSH in and see the interface, however when I try to push, the request times out.

**Comment by aymanbagabas** [comment]
Make sure you're using the right SSH key when you push to your server. Try debugging using `export GIT_SSH_COMMAND='ssh -vv'`. You could also specify the `IdentityKey` to use in your SSH config.

**Comment by donuts-are-good** [comment]
thanks, I'll give it a shot.
