### ISSUE TITLE
SSH CLI: Custom commands

### ISSUE THREAD

**Issue by FiReLScar** [charmbracelet/soft-serve#150]
It would be cool to be able to add commands to the SSH CLI, for example I want to add a command that allows the user to run `ssh git.n11.dev mirror` and it will run an existing script that updates the github mirrors.

**Comment by aymanbagabas** [comment]
Soft Serve [v0.5.0](https://github.com/charmbracelet/soft-serve/releases/tag/v0.5.0) has mirror support. You can import and mirror repos `ssh -p23231 soft-serve repo import --mirror [repo-name] [remote]`
