### ISSUE TITLE
Git tags not visible

### ISSUE THREAD

**Issue by PR454D** [charmbracelet/soft-serve#155]
Added some tags, even lightweight. but those were not displayed in soft serve.

![image](https://user-images.githubusercontent.com/77245742/188594127-c047145e-575a-419b-8425-632aebec4d59.png)

**Comment by bashbunni** [comment]
I was able to reproduce this with my own install of Soft Serve. 
To reproduce: 
```
git tag -a v0.1 -m "my version 0.1"  # on first commit
git tag -a v1.0 -m "my version 1.0"  # on second commit
```
Neither showed up in the Tags tab.
Version: soft version v0.4.0

**Comment by bashbunni** [comment]
Ah actually I forgot to push my tags. They won't show up in soft serve until you run:
`git push <remote-name> <branch-name> --tags`
or
`git push <remote-name> <tagname>`

to push the tags upstream. Let me know if you still have this issue after pushing the tags!

**Comment by PR454D** [comment]
Nope. The issue is resolved. 👍🏻
Tags are visible in the section.
