### ISSUE TITLE
Please make sure you have the correct access rights

### ISSUE THREAD

**Issue by AbhimanyuAryan** [charmbracelet/soft-serve#161]
just following this video on Windows 11: https://www.youtube.com/watch?v=UR_MWNVcsa4 and getting this error

I also tried running powershell with administrator permission same error 

```
[20:53:27]   ~\..\..\softserve on❯ git clone ssh://localhost:23231/config
Cloning into 'config'...
ssh: connect to host localhost port 23231: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by redbeardt** [comment]
I wasn't able to install via `go install` command in the video so I used the binary in [this archive](https://github.com/charmbracelet/soft-serve/releases/download/v0.4.3/soft-serve_0.4.3_Windows_i386.zip).

Running Win11 and wasn't able to reproduce.

```
❯ git clone ssh://localhost:23231/config
Cloning into 'config'...
remote: Enumerating objects: 4, done.
Receiving objects: 100% (4/4), done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
```

**Comment by aymanbagabas** [comment]
Thank you @redbeardt for verifying that. I'll go ahead and close this one, @AbhimanyuAryan feel free to re-open if you still encountering the problem.
