### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by maxdiebold-erg** [charmbracelet/soft-serve#162]
I'm not sure what's changed, but suddenly I can't connect to the local softserve server. I'm using the same keys, and the server seems to start successfully, but when I try to connect the interface appears, reads "Filter:" + a string of characters, then closes the connection.

**Comment by toby** [comment]
Hi, sorry to hear that. Can you run `ssh -vv YOURHOST` and check the output? We also have a [Slack](https://charm.sh/slack) if you want some help walking through debugging.

**Comment by maxdiebold-erg** [comment]
Hi @toby, thank you for the prompt response. That particular problem turned out to be an issue with a an module for the Kitty terminal emulator that I was using by default for ssh connections. It wasn't causing issues before, but it also wasn't relevant to the particular connection, so easy enough to avoid.

Beyond that, it must have been some time since I've restarted my desktop, because the interface updates were a surprise! It looks great. Also, there may have been changes to the Pacman systemd unit file for Arch? I'm not sure, but the `.repos` and `.ssh` directories I previously pointed to weren't being used, and instead new ones were created in `/var/lib/soft-serve`. Not a problem, but threw me for a loop.
