### ISSUE TITLE
README possibly misleading on repository visibility

### ISSUE THREAD

**Issue by sylph1o** [charmbracelet/soft-serve#165]
While reading the README for the first time, [this comment](https://github.com/charmbracelet/soft-serve/blob/0da7a8603813abba90f6446a5c2ce02d1781c5c7/README.md?plain=1#L135-L136) in the configuration example lead me to believe that any user would be able to see all repositories, i.e. soft-serve manages write access but not read access. That would seriously limit my use for soft-serve, which I find otherwise very interesting.

Exploring further lead me to issue #80, which suggests that a repository configured as `private` is only visible to users who have it their `collab-repos`. That would be the read-access management that I thought was missing. If this is true, then the README is misleading (at least, it misled me), to the detriment of soft-serve.

**Comment by aymanbagabas** [comment]
> While reading the README for the first time, [this comment](https://github.com/charmbracelet/soft-serve/blob/0da7a8603813abba90f6446a5c2ce02d1781c5c7/README.md?plain=1#L135-L136) in the configuration example lead me to believe that any user would be able to see all repositories, i.e. soft-serve manages write access but not read access. That would seriously limit my use for soft-serve, which I find otherwise very interesting.
> 
> Exploring further lead me to issue #80, which suggests that a repository configured as `private` is only visible to users who have it their `collab-repos`. That would be the read-access management that I thought was missing. If this is true, then the README is misleading (at least, it misled me), to the detriment of soft-serve.

Good catch @sylph1o!  The readme is indeed misleading.

Repositories configured as `private` are only accessible by admins and collab-users. Regular users can access all public repositories based on the `anon-access` config property.

**Comment by sylph1o** [comment]
Thanks for the quick reaction and the clarification! I look forward to trying soft-serve, it looks already very nice, and promising :smiley:
