### ISSUE TITLE
Remote actions

### ISSUE THREAD

**Issue by IngwiePhoenix** [charmbracelet/soft-serve#178]
**Is your feature request related to a problem? Please describe.**
I just tested out the public instance of this on the Charm server and I really, really love it. But the first thought I had was to control installation of projects.

For instance, I am working on a project using and written in different languages and I would love to be able to trigger an update of the deployed app:

```
git add ...
git commit -m "Version bump!"
git push github # Triggers CI/CD

# During/within CD:
if $success; then
  git push soft
fi
```

When `soft` receives a push, I would love it to automatically run a remote script to tear down the current installation, update to the new version from the new git version and start it up again.

**Describe the solution you'd like**
Within the configuration, I'd love to see an option to specify which scripts should be run and under what circumstances.

A quick idea would be:
```yaml
repos:
  - name: myapp
    # ... other options

actions:
  - for: myapp
    when: push
    by: admin
    then: sh $repo/scripts/deploy.sh
```

**Describe alternatives you've considered**
Well in general having simple actions would be neat. Since this is most likely deployed to a small server, it doesn't need something super fancy; just something that runs a script when a push is received. Or maybe for other actions, really! :)

**Additional context**
I run most of my stuff on a plain old Linux server located in a remote DC - having a little bit of deployment automation would always be welcome.

Also, you guys' TUIs are amazing. <3 Haven't had so much fun staring at my terminal in a while!

**Comment by aymanbagabas** [comment]
Hi @IngwiePhoenix

This is a great fit for [git hooks](https://git-scm.com/docs/githooks#post-update), you could add a `post-update` hook to your repository and it will run after you push to the repository. Soft Serve stores your repositories under `.repos` by default. Create your `post-update` script under `.repos/<myapp>/hooks/post-update` and then give it execute permissions `chmod +x .repos/<myapp>/hooks/post-update`.

**Comment by IngwiePhoenix** [comment]
Oh neat, didnt know that!


Thanks for the idea!
