### ISSUE TITLE
Where shall I put my `config.yaml` as a non-root user

### ISSUE THREAD

**Issue by ChanceFCC** [charmbracelet/soft-serve#181]
When I installed soft-serve as a ubuntu package, and tried run `soft serve` as non-root user `ubuntu`, I got this,

`error opening repository config.yaml: file does not exist
`

Putting `config.yaml` inside `.repo` sounds reasonable to me, but it didn't work.

**Comment by aymanbagabas** [comment]
When you first run `soft serve`, it will create a `.repos` directory with the config repo including a default `config.yaml` file. Given the error you are getting, it might be that `soft serve` is trying to create the default config repo but does not have the permissions to do so. Ensure you're running `soft serve` in `$HOME`.
