### ISSUE TITLE
No readme found.

### ISSUE THREAD

**Issue by yonas** [charmbracelet/soft-serve#182]
**Describe the bug**
The README file (eg. README.md) is not being found.

**To Reproduce**
1. `ssh -p 23231 [your server]`
2. Hit ENTER on the `config` repo
3. Notice that the README is not found.

**Expected behavior**
The README should be found and displayed.

**Environment (please complete the following information):**
 - OS: FreeBSD 13.1
 - Terminal: kitty
 - Version: [494ecb1](https://github.com/charmbracelet/soft-serve/commit/494ecb10a492309cd5031d5bd7694ea365ca0cea)

**Comment by aymanbagabas** [comment]
I cannot reproduce your issue here. I can see the readme `ssh git.charm.sh`. Do you see any errors in the logs?

**Comment by yonas** [comment]
Thanks @aymanbagabas, I'm unable to reproduce as well... strange. I'll reopen if needed.
