### ISSUE TITLE
Private repos are not that private...

### ISSUE THREAD

**Issue by fiplox** [charmbracelet/soft-serve#189]
**Describe the bug**
I suppose your config repo is marked as private.
Anyone can access it with `ssh git.charm.sh -t config`
If I create new repo and make it private, I still can access it with `-t` flag, while `ls` or `cat` says `Error: Unauthorized`

**To Reproduce**
1. Create `repo`
2. Make it private in the config (`private: true`)
3. ssh `<soft-serve server>` -t `repo`
4. See everything in the repo

**Expected behavior**
Error: Unauthorized

**Environment (please complete the following information):**
Docker compose with latest image (`image: charmcli/soft-serve:latest`)

**Comment by aymanbagabas** [comment]
Hey @fiplox, thank you for reporting this one. I will keep you posted when the fix is pushed.

**Comment by aymanbagabas** [comment]
@fiplox This is now fixed in [v0.4.2](https://github.com/charmbracelet/soft-serve/releases/tag/v0.4.2) and [v0.4.3](https://github.com/charmbracelet/soft-serve/releases/tag/v0.4.3) :)
