### ISSUE TITLE
Preserve menu items order

### ISSUE THREAD

**Issue by aymanbagabas** [charmbracelet/soft-serve#193]
Add the ability to preserve the order of repositories in the config file.

**Comment by fiplox** [comment]
Good idea, and also I discovered that `ls` command sorts in a strange way. It'd be nice if it had one of the following:
1. Alphabetical order
2. Commit time order
3. Config items order

And same goes to menu items. I think a choice in a config file would be great. And one other question is, what should order be for the repos that are not in the config file? Should it be 1 or 2?

**Comment by salasberryfin** [comment]
Hi!

I'd like to work on this and I'm taking a look at how this functionality could be implemented.

I came up with a few ideas and would like to review if it is aligned with what's expected:
- For the `ls` command, I see that the `AllRepos` function is called when no repository name is passed as argument. The slice returned by this function could be sorted first, based on the given order. A new `sort` function can be added that performs the correct type of sort and returns the sorted repositories slice. We could define a default sort type (alphabetical?) if the configuration is missing or an incorrect value is passed.
- `AllRepos` is a method with a `RepoSource` receiver. Does adding a `order` field to the `RepoSource` struct make sense? I was thinking about including this as a string field, which is passed when creating a new `RepoSource` from `NewConfig`. This would require the new `RepoOrder` configuration parameter to be part of the `Config` struct, as an environment variable.

Are these ideas aligned with the issue? If not, any feedback is welcome!

Thanks!
