### ISSUE TITLE
New install can't ssh on bound port 23231 remotely

### ISSUE THREAD

**Issue by scottgbailey** [charmbracelet/soft-serve#195]
New install can't ssh on bound port 23231 remotely. 

**To Reproduce**
1. Create a fresh OpenBSD 7.2 instance in Vlutr
2. Download latest from release branch
3. attempt to ssh <publicip> -p 23231
4. See error: kex_exchange_identification: read: Connection timed out

**Expected behavior**
I can ssh straight to the new box on port 23231. 

**Environment (please complete the following information):**
 - OS: OpenBSD 7.2
 - Terminal: Powershell, Ubuntu 20.04 LTS
 - Version 7.3.0, bash

**Additional context**
I've ran port scan via nmap and it can reach the port. shows the the Openssh version: 
23231/tcp open     ssh     OpenSSH 7.6p1 (protocol 2.0)

I can connect to it locally via ssh localhost -p 23231

**Comment by Haruki** [comment]
Did you change the config server address from localhost to something else?
I needed to change localhost to 0.0.0.0 to be able to connect remotely.

**Comment by staticfrost** [comment]
w0w, such a simple fix thank you!

**Comment by scottgbailey** [comment]
w0w, such a simple fix.

Thank you!
