### ISSUE TITLE
git lfs support

### ISSUE THREAD

**Issue by gedw99** [charmbracelet/soft-serve#218]
https://github.com/git-lfs/git-lfs/blob/main/docs/api/server-discovery.md

it uses tusd to store the actual images. https://github.com/git-lfs/lfs-test-server

This allows git users to store large images..

Its pretty cool...

**Comment by aymanbagabas** [comment]
This is something we are planning to add.

**Comment by Andonome** [comment]
An lfs server would be great. It's a great project, but I can't use it for most of my repos, as they use lfs.

**Comment by Andonome** [comment]
Any update on this?
