### ISSUE TITLE
View stashes in UI

### ISSUE THREAD

**Issue by public-rant** [charmbracelet/soft-serve#219]
Is there any interest in viewing stashes? I sometimes like to share stashes between projects in development rather than branches/commits.

**Comment by aymanbagabas** [comment]
Stashes are used locally in a local git repository, _not_ server-side. Soft Serve is a Git server that manages bare git repositories. You might be interested in [git worktree](https://git-scm.com/docs/git-worktree)

**Comment by public-rant** [comment]
All you've done is contradict me. Personally, I have a use case for sharing stashes *server side*. And I am already familiar with worktrees, thanks.
