### ISSUE TITLE
Don’t use shell commands

### ISSUE THREAD

**Issue by gedw99** [charmbracelet/soft-serve#220]
github.com/gogs/git-module shells out to the OS to use the local git binary 

go-git is pure go and then shells out only where there are missing go implements.

https://github.com/go-git/go-git

https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md

Gitea uses gio-git apparently

**Comment by aymanbagabas** [comment]
Soft Serve used to use go-git in earlier versions. It had a memory leak issue when reading lots of commits and patches, so we decided to switch to git-module. The newer versions of go-git look more performant. Somewhere down the line, we plan on switching back to go-git once all the features that we need are implemented.
