### ISSUE TITLE
Immediate crash on start if there is issues with head refs for any repo

### ISSUE THREAD

**Issue by Zaiju-code** [charmbracelet/soft-serve#235]
**Describe the bug**
Basically today one of my head refs for a branch broke somehow. Not sure exactly how that happened but I discovered that the issued caused soft-serve to immediately crash on start.

This wouldn't be the worst if it was the only repo on the server but I have several working repos that were also rendered inaccessible.

I'm aware this exception might not be handled intentionally to avoid commiting changes to a damaged repo. If so change this from a bug report to a feature request with the feature being that a degraded repo should be disabled but working repos and soft-serve should stay active. 

**To Reproduce**
1. Mess up the head ref for any branch
2. Try to start soft-serve
3. Have a bad time

**Expected behavior**
Branch or repo goes down, unrelated repos stay accessible.

**Environment (please complete the following information):**
 - OS: Arch
 - Terminal: Kitty
 - Version: 0.4.5-1

**Comment by aymanbagabas** [comment]
Thank you for reporting this bug @Zaiju-code. The issue is now resolved in [v0.4.7](https://github.com/charmbracelet/soft-serve/releases/tag/v0.4.7).
