### ISSUE TITLE
Authorized User abilities are not clear

### ISSUE THREAD

**Issue by Andonome** [charmbracelet/soft-serve#237]
Authorized non-admin users cannot seem to create new repositories.
I don't know if this is by design - the initial docs aren't clear.

**To Reproduce**

1. Install soft-serve
1. Push a repo called `lk`
1. Add user nimbus
	1. Generate ed25519 ssh key.
1. Add the following config:
	1. (putting in correct keys)

```
name: Local Soft
host: localhost
port: 23231
anon-access: read-only
allow-keyless: true
repos:
  - name: Home
    repo: config
    private: true
    note: "Configuration and content repo for this server"
    readme: README.md
  - name: Linux Knowledge Base
    repo: lk
    private: false
    note: "Linux Knowledge Base"
    readme: README.md

users:
  - name: ghost
    admin: true
    public-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NNE5AAAAIF7g6oP6+DyFhkIrN4pRcvsQ7RgNavEyzN2kH8yOB6mA randomEmail@email.net
  - name: nimbus
    admin: false
    collab-repos:
      - lk
    public-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NNE5AAAAICMiTFinyHxMh02lT3RWrQCPxH/99EmHrsBGEwpisDuh another@email.uk

```

**Expected behavior**

I thought user *nimbus* would be able to push new repositories, being a registered user, but I can only allow new repo creation by making nimbus an admin.

When pushing a new repo, *nimbus* receive the standard 'not authorized' message.
However, this non-admin user *can* push to `lk`, from the `collab-repos` section, so the ssh key must have been accepted.

I'm not sure if my expectations or my setup is wrong.

**Environment:**

Arch Linux

**Comment by aymanbagabas** [comment]
@Andonome thank you for reporting this issue.

This was actually the behavior of Soft Serve, non-admin users cannot create new repositories unless they are contributed. However, this is changed in the _new_ v0.5 Soft Serve, registered users _can_ create new repositories now.

We have added new [authentication](https://github.com/charmbracelet/soft-serve#authentication) and [authorization](https://github.com/charmbracelet/soft-serve#authorization) sections that explain and clarify user abilities. Let us know if you find any bugs or issues :)

To migrate to v0.5, check out the migration notes [here](https://github.com/charmbracelet/soft-serve/releases/tag/v0.5.0) as this release includes breaking changes.

**Comment by Andonome** [comment]
This all looks great. I'll test it once Arch Linux has the updated soft-serve package.

**Comment by Andonome** [comment]
Everything works, and user permissions are clear.

Thanks for the great work!
