### ISSUE TITLE
Question about soft serve

### ISSUE THREAD

**Issue by vsoch** [charmbracelet/soft-serve#239]
Hi! I like the design of the navigation sidebar and a main viewport here:

![image](https://user-images.githubusercontent.com/814322/229382413-289becd9-42b3-4411-a066-8e96cb532afc.png)

But I tested the current soft serve, and it seems very different. Is this an old style?

**Comment by caarlos0** [comment]
hey @vsoch!

Yes, the current style is the one you can see in the gif in our [README](https://github.com/charmbracelet/soft-serve) and/or by running `ssh git.charm.sh`.

**Comment by vsoch** [comment]
@caarlos0 I already tried that - the design looks completely different. Here is the entry:

![image](https://user-images.githubusercontent.com/814322/229587956-1bbe2713-adef-4546-920e-ca1f77eb8e0c.png)

and a repository page:

![image](https://user-images.githubusercontent.com/814322/229588012-aa2b1240-5062-4659-a6ae-0df1104a5e29.png)

I'm specifically interested in the design shown in the gif that is screenshotted in my original issue description. Thanks!

**Comment by aymanbagabas** [comment]
Hi @vsoch! You can find the old design in versions prior to v0.4.0. Take a look at [v0.3.3](https://github.com/charmbracelet/soft-serve/tree/v0.3.3)

**Comment by vsoch** [comment]
Great - that's what I was interested in. Thank you!
