### ISSUE TITLE
Anonymous users cannot clone or pull public repositories with read-only anonymous access

### ISSUE THREAD

**Issue by grobe0ba** [charmbracelet/soft-serve#247]
**Describe the bug**
Anonymous users cannot clone or pull public repositories with
read-only anonymous access.

**To Reproduce**

```
$ # These are to ensure you connect as an anonymous user
$ export GIT_SSH_COMMAND='ssh -i /dev/null'
$ unset SSH_AUTH_SOCK
$ # Proceed to attempt to clone
$ git clone ssh://soft:23231/publicrepo
Cloning into 'publicrepo'...
Load key "/dev/null": invalid format
fatal: protocol error: unexpected 'you are not authorized to do this'
```

**Expected behavior**

Read-only access does not imply an inability to clone repositories,
especially since the repository can be browsed in the UI. The
repository should be cloned.

**Environment**

-   OS: RHEL 8.7 / Alpine 3.16 / 9front
-   Version: 5149978832d379c611b81cc0e6e029bb17469bb6

**Additional context**

This would appear to be caused by soft-serve immediately rejecting
any attempt to use the `git-upload-pack` command. The ```git-upload-pack```
 command is used to inform the server which packs are needed and is a
*required* part of the protocol.

**Comment by aymanbagabas** [comment]
Hi @grobe0ba, a lot has changed in the new [v0.5.0](https://github.com/charmbracelet/soft-serve/releases/tag/v0.5.0) version, could you give that a try and see if the problem still persist?

**Comment by grobe0ba** [comment]
The issue does seem to have been solved.
Thanks!
