### ISSUE TITLE
Use TUI with other git repos?

### ISSUE THREAD

**Issue by chaxor** [charmbracelet/soft-serve#248]
I really like the TUI for viewing the git repo here - is there a way to use this TUI to view and interact with *any* given git repo?

Perhaps one (though there's likely a better) solution would be to separate the `ui` directory from the internals of this package (I realize that may be more difficult than it seems).

**Comment by aymanbagabas** [comment]
@chaxor this is not possible as of now since the `ui` is closely coupled with the `server`. However, PRs are welcome! Feel free to take a stab at this :)

**Comment by aymanbagabas** [comment]
You can now browse local repositories by running `soft` in a git repo or `soft browse <repo path>`
