### ISSUE TITLE
migrate-config doesn't bring descriptions with it?

### ISSUE THREAD

**Issue by decentral1se** [charmbracelet/soft-serve#250]
**Is your feature request related to a problem? Please describe.**

It's quite tedious to create descriptions for a large number of respositories.

This was done in < 0.5 but did not get carried over with >= 0.5 afaiu.

**Describe the solution you'd like**

It's added to the migration script.

**Describe alternatives you've considered**

I did it manually for all of them.

**Additional context**

In general, managing each repo description by hand is a bit tedious.

It's a great usability win for browsers if that description is there.

Could it be an idea to pull the `# ...` title from a README or some other convention? That would be nice.

(PS. Thanks for the v0.5 work, it's great stuff!)

**Comment by aymanbagabas** [comment]
Hi @decentral1se, `migrate-config` _should_ migrate repo descriptions and names as you can see in [`migrate-config.go`](https://github.com/charmbracelet/soft-serve/blob/main/cmd/soft/migrate_config.go#L245-L272). Did you encounter any errors during the migration?

**Comment by decentral1se** [comment]
@aymanbagabas aha, i see. Yeh I ran into an error which I sadly don't have logs any more for but it was basically the `config` -> `.soft-serve` migration and it *seeeeemed* like an error from `git branch -M ...` command. I haven't looked into it as I managed to migrate anyhow. Will close this one off for now, thanks!
