### ISSUE TITLE
Add support for Git LFS

### ISSUE THREAD

**Issue by toby** [charmbracelet/soft-serve#26]
The Git [Large File Storage Extension](https://git-lfs.github.com) doesn't currently work with Soft Serve, but it should. Current errors include:

```
$ git push origin main 
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://localhost/x-wombat/info/lfs.locksverify false
batch request: unexpected end of JSON inputB/s
```
and after disabling the lock:

```
$ git config lfs.https://localhost/x-wombat.git/info/lfs.locksverify false
$ git push origin main 
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done.                                                                                                                   
batch request: unexpected end of JSON input
error: failed to push some refs to 'ssh://localhost:23231/x-wombat'
```

**Comment by Andonome** [comment]
I'm getting a different error, but still no dice.
```
batch request: invalid character 'S' looking for beginning of value                               
error: failed to push some refs to 'ssh://localhost:23231/core'
```

**Comment by Andonome** [comment]
Are there any docs on setting this up? It looks like I need to set up the http support.

**Comment by aymanbagabas** [comment]
> Are there any docs on setting this up? It looks like I need to set up the http support.

No extra setup is needed, Soft Serve runs its own HTTP server with LFS support. It also supports the new pure-SSH Git LFS protocol. https://github.com/charmbracelet/soft-serve/pull/360
