### ISSUE TITLE
Docker: Failing to create new repositories

### ISSUE THREAD

**Issue by NCRoxas** [charmbracelet/soft-serve#260]
**Describe the bug**
When using the docker image of the newest version of soft-serve it's impossible to create new repositories, either via the `ssh -p 23231 localhost repo create icecream` command or locally via `git push`. 
After creating a new repo with `ssh -p 23231 localhost repo create icecream` and then checking with `ssh -p 23231 localhost repo info icecream` the command exits with `Error: reference does not exist`. When pushing a locally created repo it fails with 
```
Enumerating objects: 3, done.
...
remote: env: can't execute 'bash': No such file or directory
To ssh://git.example.com:23231/test
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git.example.com:23231/test'
```

Installing soft-serve without docker works as expected.

**To Reproduce**
1. Start a fresh docker container with the latest version of soft-serve
2. Try to create a new repository
3. See error

**Expected behavior**
No error when creating/editing repositories.

**Screenshots**
![error](https://user-images.githubusercontent.com/6978595/236183129-b917fba9-344c-4021-98cf-a808d4af23a7.png)

**Environment**
 - OS: Linux
 - Version: v0.5.1

**Comment by aymanbagabas** [comment]
Sorry about that @NCRoxas. This is related to https://github.com/charmbracelet/soft-serve/issues/251.

There was an issue publishing our v0.5.1 Docker images from yesterday and it should be fixed now. Could you try pulling the latest image again, verify the version number, and try again?

```
docker pull charmcli/soft-serve:latest
# Or more specifically
docker pull charmcli/soft-serve:v0.5.1
# You can also use ghcr.io/charmbracelet/soft-serve:latest
```
