### ISSUE TITLE
"repo" not in the list of available commands

### ISSUE THREAD

**Issue by davidmritter** [charmbracelet/soft-serve#288]
Not sure what the cause of this is, but when I try running`ssh git.charm.sh repo tree soft-serve` i get:
```
Soft Serve is a self-hostable Git server for the command line.

Usage:
  ssh git.charm.sh [command]

Available Commands:
  cat         Outputs the contents of the file at path.
  git         Perform Git operations on a repository.
  help        Help about any command
  ls          List file or directory at path.
  reload      Reloads the configuration

Flags:
  -h, --help   help for ssh

Use "ssh git.charm.sh [command] --help" for more information about a command.
```
I am using Arch Linux with: OpenSSH_9.3p1, OpenSSL 3.0.8 7 Feb 2023

**Comment by aymanbagabas** [comment]
Hi @davidmritter, sorry for the inconvenience. We _just_ updated our Soft Serve infrastructure to the latest version v0.5. You should be able to `ssh git.charm.sh repo tree soft-serve` now :)
