### ISSUE TITLE
Soft serve doesn't recognize multiple authentication keys.

### ISSUE THREAD

**Issue by secondary-smiles** [charmbracelet/soft-serve#293]
**Describe the bug**
I use ssh to remote into a few machines so I have a few different keys `ssh-add`'ed a lot of the time. However, when using soft-serve, it won't recognize my admin key unless I specify the `-o "IdentitiesOnly=yes` flag which can be very cumbersome.

**To Reproduce**
1. Setup soft-serve
2. `ssh-add` a non-admin key
3. Attempt to use soft-serve (eg, `ssh -i ~/.ssh/id_ed25519 -p 23231 localhost help`
4. User is not logged in

**Expected behavior**
On a normal `sshd` server, I can have multiple keys added as long as I include the correct one.

**Environment (please complete the following information):**
 - OS: Linux and Mac (reproduced on both)
 - Terminal kitty, iTerm2
 - Version `soft version v0.5.3 (b07de74)`

**Comment by aymanbagabas** [comment]
Hi @secondary-smiles, could you try building Soft Serve from `main`? This issue is resolved in https://github.com/charmbracelet/soft-serve/commit/f851adb2faa6eb6281fbf55bb004294ace85a50a

**Comment by aymanbagabas** [comment]
> I don't know go at all so I have no idea if this is an issue with my go install on the remote machine (I ran `yum install go`) or if it's a bug.

This is a bug in Soft Serve, it uses new symbols introduced in go1.20 but the package only requires go1.18. Using go1.20 should solve the issue here. Try using the latest [golang version](https://go.dev/doc/install).
