### ISSUE TITLE
set-admin false doesn't work

### ISSUE THREAD

**Issue by NCRoxas** [charmbracelet/soft-serve#298]
**Describe the bug**
After creating a new user the user is always admin. Using the command `ssh -p 23231 localhost user set-admin test false` doesn't work.

**To Reproduce**
1. `ssh -p 23231 localhost user create test`
2. `ssh -p 23231 localhost user set-admin test false`
3. `ssh -p 23231 localhost user info test`
4. See test user is still Admin

Also it would be great when creating new users they would not instantly get the admin role.

Edit: I just found out it's working maybe? Some admins seem to not have access to every repository. Maybe it's a visual bug?

**Comment by aymanbagabas** [comment]
> Edit: I just found out it's working maybe? Some admins seem to not have access to every repository. Maybe it's a visual bug?

That's correct, it's a visual bug. The fix be in the next patch release :)
