### ISSUE TITLE
README path is hard coded

### ISSUE THREAD

**Issue by jparris** [charmbracelet/soft-serve#31]
First off I just wanted to say this is nice little project that fills the need of wanting to self host some private git repos and not needing a full blown web app like gitea.

Looking at loadRepo the README path is hard coded. I'd like to be able to customize this because I make use of [github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes)'s alternative path `/docs/readme.md`.

**Comment by bolshoytoster** [comment]
I've opened a pull request that should resolve this with the environment variable `SOFT_SERVE_README_PATH`.
