### ISSUE TITLE
unknown command "user" for ""

### ISSUE THREAD

**Issue by ShayneLee8** [charmbracelet/soft-serve#317]
windows 11
git bash  
when execute
`
$ ssh -p 23231 localhost user --help
`
Get as follows
`
Error: unknown command "user" for ""
Run ' --help' for usage.

`

**Comment by shantanoo-desai** [comment]
shouldn't it be:

```
ssh -p 23231 user@localhost <your command here>
```
or something like this:

```
ssh -p 23231 -l user localhost <your command here>
```
```

**Comment by ShayneLee8** [comment]
> shouldn't it be:
> 
> ```
> ssh -p 23231 user@localhost <your command here>
> ```
> 
> or something like this:
> 
> ```
> ssh -p 23231 -l user localhost <your command here>
> ```

I execute on the Windows Docker desktop。
I followed suit, but still haven't solved the problem， 
docker info
![image](https://github.com/charmbracelet/soft-serve/assets/17796459/ee6b0f3f-bec2-48ba-9c51-cd50694db238)

ssh config:
![image](https://github.com/charmbracelet/soft-serve/assets/17796459/1c230fc2-4358-4730-9bdf-075b2f6a3df3)

**Comment by ShayneLee8** [comment]
I have found the cause of the problem, it was my own mistake. I made a mistake in writing the host for. ssh/config.
The correct writing method is as follows
![image](https://github.com/charmbracelet/soft-serve/assets/17796459/e03a881b-64a5-4b0c-8e08-cc0781570d9d)
