### ISSUE TITLE
Can't SSH into soft serve remotely, only localy

### ISSUE THREAD

**Issue by JirR02** [charmbracelet/soft-serve#319]
I was able to set up my soft serve server on a rock pi 3 in docker and wanted to make it accessible remotely with cloud flare.

I was able to set up the Cloudflare Tunnel by linking git.mydomain.com to ssh://ipofserver:23231. When I try to ssh into it ssh wont load the soft serve TUI. But when I access the soft serve server localy, it works. 

Any ideas how to solve this?

Cheers,

Jay

**Comment by EgorGorshen** [comment]
**Unable to Clone Repository (config)**

I wanted to inform you about an issue I am experiencing while attempting to run the Git server on my server. Unfortunately, I am unable to successfully clone the repository from either my computer or the server itself. Everytime I try, I encounter the following error message: "Cloning into 'config'... fatal: protocol error: unexpected 'invalid repo'."

I have made several attempts to resolve this problem, but I have been unsuccessful so far. 

Thank you for your attention to this matter.
