### ISSUE TITLE
support push options

### ISSUE THREAD

**Issue by seankhliao** [charmbracelet/soft-serve#327]
**Is your feature request related to a problem? Please describe.**
With git hook support, we can run trigger CI,
but now I want to configure or skip CI sometimes.

**Describe the solution you'd like**
I'd like to use git push options which are passed through to my git hook.
Eg gitlab supports them: https://docs.gitlab.com/ee/user/project/push_options.html

**Describe alternatives you've considered**
add directives in the commit message
but that's not a particularly clean way of doing things (ci isn't really part of the change being made).

**Comment by aymanbagabas** [comment]
Hi @seankhliao, you could use Soft Serve hooks located in your config directory to integrate git push option into your workflow. You could write a _common_ `pre-receive` hook in `$SOFT_SERVE_DATA_PATH/hooks/pre-receive` that uses `$GIT_PUSH_OPTION_COUNT` and `$GIT_PUSH_OPTION_N` (N is an integer starting at 0) to parse your git push options. Hooks under `$SOFT_SERVE_DATA_PATH/hooks` will run for all projects served by Soft Serve.

Let me know if this helps :)

**Comment by seankhliao** [comment]
I did try but:

```
$ git push -v -o ci.skip                                               
Pushing to lucid-git:helloworld
fatal: the receiving end does not support push options
fatal: the remote end hung up unexpectedly
```

**Comment by aymanbagabas** [comment]
@seankhliao looking more into this, we need to add `receive.advertisePushOptions = true` to Soft Serve gitconfig
