### ISSUE TITLE
First run on Windows fails with mkdir error

### ISSUE THREAD

**Issue by stevesimmons** [charmbracelet/soft-serve#33]
I am running Windows 11. After downloading soft-serve_0.1.0_Windows_x86_64.zip and extracting the .exe file, running `soft` gives:

```
C:\Users\MyName>soft
2021/12/09 08:21:04 mkdir : The system cannot find the path specified.
```

This error is repeated for trying `soft --help`, `soft -h`, `soft /?` and any other likely command-line switches for help.

Whereas when I try the .deb package in Ubuntu running in WSL2, I get the expected result:

```
MyName@MyComputer:~$ soft
2021/12/09 08:29:58 Starting SSH server on :23231
```

**Comment by ten24bytes** [comment]
I'm also facing this issue.

**Comment by meowgorithm** [comment]
Hi! Confirming that I can reproduce this on Windows.

**Comment by meowgorithm** [comment]
Thanks for flagging this everyone. This is now working in `main` and will be available in the next release. And by all means, please let us know if you encounter any more issues on Windows.
