### ISSUE TITLE
Bug report: `readme.md` not rendered on repo page

### ISSUE THREAD

**Issue by stepbrobd** [charmbracelet/soft-serve#347]
**Describe the bug**

"No readme found." is displayed when the filename is `readme.md`.

**To Reproduce**

1. I made my instance public, please go to `ssh git.stepbrobd.com`.
2. Navigate to repo: `stepbrobd/dotfiles` or `stepbrobd/git.stepbrobd.com`
3. You'll be able to see repo readme is not rendered, and "No readme found." is displayed.
4. Navigate to Files -> readme.md, the file renders just fine.

**Expected behavior**

In the following line, readme files should be rendered regardless of casing, but `readme.md` is not rendered.

https://github.com/charmbracelet/soft-serve/blob/191b8320a037dbb30fa36630b785ff4674c16d64/server/backend/utils.go#L19

https://github.com/charmbracelet/soft-serve/blob/8d41446964fc2672f8ed374055381c641e39dff0/server/ui/pages/repo/readme.go#L32

**Screenshots**

<img width="808" alt="Screenshot 2023-07-24 at 22 06 30" src="https://github.com/charmbracelet/soft-serve/assets/81826728/32093a7d-af20-4ace-b39c-112b8ddac078">

<img width="808" alt="Screenshot 2023-07-24 at 22 06 51" src="https://github.com/charmbracelet/soft-serve/assets/81826728/49add633-b50a-4ffe-b7ce-37b67d734e9b">

**Environment (please complete the following information):**

 - OS: linux, firecracker vm, fly.io
 - Terminal: iterm2
 - Version: `charmcli/soft-serve:v0.5.5` hosted on fly.io

**Additional context**

N/A

**Comment by stepbrobd** [comment]
Soft Serve configs shared here: https://github.com/charmbracelet/soft-serve/issues/348#issuecomment-1662889918

**Comment by aymanbagabas** [comment]
This is fixed in `main` but not yet in v0.5.5
