### ISSUE TITLE
Unreadable on light theme

### ISSUE THREAD

**Issue by TeddyDD** [charmbracelet/soft-serve#37]
TUI is almost unreadable with light color theme in terminal
![screen-2021-12-09-220819](https://user-images.githubusercontent.com/4397533/145476157-cb65f066-4ce5-4ba9-a3b3-486e838a15f3.png)

**Comment by meowgorithm** [comment]
Hi! Thanks for flagging. We just pushed [a branch](https://github.com/charmbracelet/soft-serve/tree/light-bg-support) with basic support for light backgrounds.

**Comment by meowgorithm** [comment]
Thanks again for the heads up! The fix has has been merged into `main` and will be available in the next release.
