### ISSUE TITLE
Bug report: unable to push/import large repo

### ISSUE THREAD

**Issue by stepbrobd** [charmbracelet/soft-serve#376]
Please see https://github.com/charmbracelet/soft-serve/issues/348

The same problem still exist in v0.6.0, same configuration, same machine.

Usage stayed pretty low throughout the entire time.

![Screenshot 2023-08-28 at 10 42 58](https://github.com/charmbracelet/soft-serve/assets/81826728/101b6fef-8747-4381-8ad1-6af300ad503b)

## Push:

Client:
```shell
$ git push
[wait about 2min]
Connection to git.stepbrobd.com closed by remote host.
```

Soft Serve:
```shell
[info] 2023-08-28 14:11:30 ERRO ssh: failed to handle git service service=git-receive-pack err="signal: killed" repo=stepbrobd/nixpkgs
```

## Import:

Client:
```shell
$ ssh git.stepbrobd.com repo import stepbrobd/nixpkgs https://github.com/stepbrobd/nixpkgs
[wait about 5min]
Connection to git.stepbrobd.com closed by remote host.
```

Soft Serve:
```shell
[info] 2023-08-28 14:30:10 INFO backend: importing repository name=stepbrobd/nixpkgs remote=https://github.com/stepbrobd/nixpkgs path=/data/repos/stepbrobd/nixpkgs.git

[info] 2023-08-28 14:30:10 INFO backend: running import name=stepbrobd/nixpkgs

[error] could not proxy TCP data to/from instance: failed to copy (direction=server->client, error=Connection reset by peer (os error 104))

[error] could not proxy TCP data to/from instance: failed to copy (direction=client->server, error=Transport endpoint is not connected (os error 107))

[error] could not proxy TCP data to/from instance: failed to copy (direction=client->server, error=Transport endpoint is not connected (os error 107))
```

**Comment by stepbrobd** [comment]
I was using default `SOFT_SERVE_SSH_IDLE_TIMEOUT` and `SOFT_SERVE_SSH_MAX_TIMEOUT`, just tested 0 and 9999 for both, the problem still persists:

## Push

### 0 (https://github.com/stepbrobd/git.stepbrobd.com/commit/7c51cbf79dd77d2338127b83bd311c06bfd61f43):

```shell
$ git push
[wait about 2min]
Connection to git.stepbrobd.com closed by remote host.
```

```shell
[info] 2023-08-28 19:08:29 ERRO ssh: failed to handle git service service=git-receive-pack err="signal: killed" repo=stepbrobd/nixpkgs
```

### 9999 (https://github.com/stepbrobd/git.stepbrobd.com/commit/4a33be88261901b7c251b208f92717c43f497698):

```shell
$ git push
[wait about 2min]
Connection to git.stepbrobd.com closed by remote host.
```

```shell
[info] 2023-08-28 19:18:34 ERRO ssh: failed to handle git service service=git-receive-pack err="signal: killed" repo=stepbrobd/nixpkgs
```

## Import

### 0 (https://github.com/stepbrobd/git.stepbrobd.com/commit/7c51cbf79dd77d2338127b83bd311c06bfd61f43):

```shell
$ ssh git.stepbrobd.com repo import stepbrobd/nixpkgs https://github.com/stepbrobd/nixpkgs
[wait about 2min]
Connection to git.stepbrobd.com closed by remote host.
```

```shell
[info] 2023-08-28 19:12:00 INFO backend: importing repository name=stepbrobd/nixpkgs remote=https://github.com/stepbrobd/nixpkgs path=/data/repos/stepbrobd/nixpkgs.git

[info] 2023-08-28 19:12:00 INFO backend: running import name=stepbrobd/nixpkgs

[error] could not proxy TCP data to/from instance: failed to copy (direction=server->client, error=Connection reset by peer (os error 104))
```

### 9999 (https://github.com/stepbrobd/git.stepbrobd.com/commit/4a33be88261901b7c251b208f92717c43f497698):

```shell
$ ssh git.stepbrobd.com repo import stepbrobd/nixpkgs https://github.com/stepbrobd/nixpkgs
[wait about 2min]
Connection to git.stepbrobd.com closed by remote host.
```

```shell
[info] 2023-08-28 19:20:44 INFO backend: importing repository name=stepbrobd/nixpkgs remote=https://github.com/stepbrobd/nixpkgs path=/data/repos/stepbrobd/nixpkgs.git

[info] 2023-08-28 19:20:44 INFO backend: running import name=stepbrobd/nixpkgs

[error] could not proxy TCP data to/from instance: failed to copy (direction=server->client, error=Connection reset by peer (os error 104))
```

**Comment by aymanbagabas** [comment]
I just tested pushing and importing the repository to my testing machine (2 vCPUs / 4gb mem) and it works fine :/ 

Are you managing the server yourself at fly.io? It seems like the server running Soft Serve resets SSH connections after 2 minutes causing Soft Serve to abort pushing the repository. `git-receive-pack` is the Git service responsible for handling repository pushes. It reads the connection and transfers Git objects.

<img width="555" alt="Screenshot 2023-08-28 at 4 41 03 PM" src="https://github.com/charmbracelet/soft-serve/assets/3187948/4c94dbdf-4c68-4672-a115-4386d721086b">

<img width="614" alt="Screenshot 2023-08-28 at 4 45 14 PM" src="https://github.com/charmbracelet/soft-serve/assets/3187948/028a7d9b-1cdb-4846-88a3-cf9d700c39ba">

<img width="696" alt="Screenshot 2023-08-28 at 4 46 41 PM" src="https://github.com/charmbracelet/soft-serve/assets/3187948/3c2cd4a5-dd4f-4576-a1a0-886c8573f78c">

**Comment by stepbrobd** [comment]
Thanks a lot! I searched for TCP timeout on Fly.io community and it seems like they enforce a 60 sec timeout for TCP connections.

Since this is a hosting platform issue, closing this issue.

**Comment by benwaffle** [comment]
We (fly.io) have removed some of the TCP timeout restrictions - see https://community.fly.io/t/tcp-idle-timeouts-restrictions-have-been-removed/15160. I'm curious if you're still experiencing the issue.

**Comment by stepbrobd** [comment]
I think removing the timeout restrictions should help with this issue, but my problem was resolved by setting `GIT_SSH_COMMAND=ssh -o TcpKeepAlive=no -o ServerAliveInterval=10` before the removal of timeout restrictions.
