### ISSUE TITLE
Config does not honor host and port settings

### ISSUE THREAD

**Issue by shadowrylander** [charmbracelet/soft-serve#38]

**Comment by meowgorithm** [comment]
Thanks for reporting. I can reproduce this—we'll look into it.

**Comment by meowgorithm** [comment]
Thanks again for the heads up. This fix is now in `main` and will be available in the next release.

**Comment by shadowrylander** [comment]
Got it; sorry for the late reply! Thank you kindly for the help!

**Comment by meowgorithm** [comment]
No problem, thanks again for letting is now. You can find the fix in Soft Serve [v0.1.2](https://github.com/charmbracelet/soft-serve/releases/tag/v0.1.2).

**Comment by shadowrylander** [comment]
@meowgorithm Ah, quick note: it's still stating `2021/12/12 14:49:07 Starting SSH server on :23231`, while serving soft on `:222`.

**Comment by zQueal** [comment]
I just now built soft-serve from source via go. After setting the environment variable `SOFT_SERVE_PORT=2022` and then running `soft` I still get;

```cmd
2021/12/13 02:19:58 Starting SSH server on localhost:23231
```

**Comment by meowgorithm** [comment]
@zQueal I'm afraid I can't reproduce your error. I'm able to run set the port via the environment like so:

```
$ SOFT_SERVE_PORT=8000 soft
2021/12/12 21:37:24 Starting SSH server on localhost:8000
```

@shadowrylander Thanks for the heads up — we may have missed something in the patch. I'll give this one another look shortly.

**Comment by zQueal** [comment]
Initial issue seems to be a disconnect between bash and [elvish shell](https://github.com/elves/elvish).

I had to set the environment variables in `.bashrc`, load them, and then import them into my `rc.elv` as follows;

```elvish
var SOFT_SERVE_PORT = (get-env SOFT_SERVE_PORT)
var SOFT_SERVE_HOST = (get-env SOFT_SERVE_HOST)
var SOFT_SERVE_REPO_PATH = (get-env SOFT_SERVE_REPO_PATH)
var SOFT_SERVE_INITIAL_ADMIN_KEY = (get-env SOFT_SERVE_INITIAL_ADMIN_KEY)
```

Which then made them available under elvish. The server is running correctly now, however, I can't possibly connect because there's no information on __where__ to put the config file. I've tried just about every single directory I can possibly think of...

**Comment by meowgorithm** [comment]
@zQueal That’s good to know about Elvish. We’re fans over here.

As for the config, it's actually a config _repo_ which gets created at `SOFT_SERVE_REPO_PATH` on startup if it doesn't exist. So the config file in that repo must be configured with `git`.

**Comment by zQueal** [comment]
>So the config file in that repo must be configured with git.

Am I missing something here? There's nothing there? I've additionally created a `config.yaml` and put it in this directory, trying to run the server. Still nothing.

```cmd
root in {host} in ~/.repos/config on  master
❯ ls
config  HEAD  info  objects  refs
```

**Comment by xuwhao** [comment]
> > So the config file in that repo must be configured with git.
> 
> Am I missing something here? There's nothing there? I've additionally created a `config.yaml` and put it in this directory, trying to run the server. Still nothing.
> 
> ```batchfile
> root in {host} in ~/.repos/config on  master
> ❯ ls
> config  HEAD  info  objects  refs
> ```

I also cannot connect the `soft`, and cannot found config.yaml file.

```
❯ pwd
/root/soft-serve/data/repos/config
❯ ls
HEAD  config  info  objects  refs
```

I use docker to run `soft`. The container's status shows as following.

![image](https://user-images.githubusercontent.com/46437721/145810815-16672491-1d62-4c22-a39c-71e2b78d2dd3.png)

![image](https://user-images.githubusercontent.com/46437721/145810787-6e4eeb1b-3244-45cf-b07a-482a6f7cfc86.png)

when I try to connect the `soft`, I got an error.

```
❯ ssh localhost -p 23231 -v
OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to localhost [127.0.0.1] port 23231.
debug1: Connection established.
debug1: identity file /root/.ssh/id_rsa type 0
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: identity file /root/.ssh/id_dsa type -1
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: identity file /root/.ssh/id_ecdsa_sk type -1
debug1: identity file /root/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: identity file /root/.ssh/id_ed25519_sk type -1
debug1: identity file /root/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /root/.ssh/id_xmss type -1
debug1: identity file /root/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4
kex_exchange_identification: Connection closed by remote host
```

**Comment by meowgorithm** [comment]
Confirming `host` and `port` are still being ignored by `config.yaml` (which exists in a bare Git repo, not on the filesystem).

**Comment by meowgorithm** [comment]
Hi everyone. As it turns out, the `host` and `port` in the config are actually for changing the appearance of of clone commands in the TUI (.i.e. `git clone ssh://localhost:23231/my-repo`). A lot of times you'll need to change these settings if the host and/or port differ from the actual host and port the server is listening on.

For example, if the SSH server is listening on `0.0.0.0:23231` but the server is reverse-proxied behind `burrito.example.com:22`, you'd set host and port to...

```yaml
host: burrito.example.com
port: 22
```

...so that your clone commands read correctly (i.e. `ssh ssh://burrito.example.com/my-repo`).

So, to set the actual host and port you should use the `SOFT_SERVE_HOST` and `SOFT_SERVE_PORT` environment variables.

**Comment by shadowrylander** [comment]
> So, to set the actual host and port of the server itself you should use the `SOFT_SERVE_HOST` and `SOFT_SERVE_PORT` environment variables.

Would it be possible to implement a way of setting these in the config itself, where restarting the server activates them? I'd like all the settings to be in the same place, if possible! 😅

**Comment by zQueal** [comment]
Cloned master, built with `go build` and it seems to be working!
