### ISSUE TITLE
Cannot use `settings` commands due to missing PostgreSQL columns

### ISSUE THREAD

**Issue by JJGadgets** [charmbracelet/soft-serve#380]
**Describe the bug**
I cannot change global settings `allow-keyless` and `anon-access` when using Soft Serve with a PostgreSQL database, due to the relevant tables not having the columns created.

**To Reproduce**
```
❯ ssh admin@softserve settings anon-access read-only
Error: pq: column "anon_access" does not exist

❯ ssh admin@softserve settings allow-keyless true
Error: pq: column "allow_keyless" does not exist
```

**Expected behavior**
The settings be successfully changed.

**Screenshots**
Terminal snippet attached above in "**To Reproduce**"

**Environment (please complete the following information):**
 - OS: Client: Void Linux & Android, Server: Kubernetes
 - Terminal: WezTerm & Termux
 - Version: v0.6.0, upgraded from v0.5.5 main snapshot due to testing PostgreSQL support (#363). Both versions had the same issue.

**Additional context**
My Kubernetes deployment of Soft Serve can be found at https://github.com/JJGadgets/Biohazard/blob/5d3e190d8412abeab99f9a8fef5164c944056965/kube/deploy/apps/soft-serve/app/hr.yaml

I upgraded from the Docker image with tag and hash `v0.5.5-devel@sha256:96b84fef416c1c5264b57c63f500ade37ba7b1203bec875890a2af933ebdce0b`

I'm open to dropping and recreating the database if needed, I haven't done much beyond pushing repos and setting them to private, but I have not touched the database myself yet if further debugging of the bugged state is needed.

I have not checked the commits for any new Postgres related changes since the main snapshot image I was previously running was first built, so if there were any changes, they could be related to my issue and the v0.6.0 release with a fresh database could be unaffected. Just a consideration.

**Comment by aymanbagabas** [comment]
Thanks for reporting this bug. I can confirm it is being fixed in #383. I will enable the CI for Postgres and release the fix in v0.6.1

**Comment by JJGadgets** [comment]
No worries, thanks for the quick fix. Want me to test the latest snapshot?

**Comment by aymanbagabas** [comment]
> No worries, thanks for the quick fix. Want me to test the latest snapshot?

Go for it! A new release is being published [right now](https://github.com/charmbracelet/soft-serve/actions/runs/6175971539/job/16763938407)

**Comment by JJGadgets** [comment]
Confirmed to be fixed. Thanks! 🎉
