### ISSUE TITLE
UI: display branch/tag commit and sort them by commit date

### ISSUE THREAD

**Issue by aymanbagabas** [charmbracelet/soft-serve#382]
**Describe the bug**
Branches and tags TUI currently waste a lot of space and give a little context to what is being displayed. Instead, it would be nice to display the branch/tag referenced commit, and commit date, and sort them by commit date.

![image](https://github.com/charmbracelet/soft-serve/assets/3187948/8883791f-011c-40d8-adc5-fcd4793eccba)
![image](https://github.com/charmbracelet/soft-serve/assets/3187948/22badaa3-33fc-42b7-adfe-16979344b3a9)

**Comment by emilaleksanteri** [comment]
Hi, would the idea be to display the most recent commit on set branch on its own tab with the given info to give extra context for each branch?

**Comment by aymanbagabas** [comment]
> Hi, would the idea be to display the most recent commit on set branch on its own tab with the given info to give extra context for each branch?

Hey @emilaleksanteri, the idea is to sort the branches/tags based on their referenced commit date and display the commit title and hash

**Comment by emilaleksanteri** [comment]
> > Hi, would the idea be to display the most recent commit on set branch on its own tab with the given info to give extra context for each branch?
> 
> 
> 
> Hey @emilaleksanteri, the idea is to sort the branches/tags based on their referenced commit date and display the commit title and hash

@aymanbagabas that sounds like a really cool idea! Do you mind if I work on this or is the issue taken already?

**Comment by aymanbagabas** [comment]
Hey @emilaleksanteri, sorry I didn't see your comment. I've implemented this in [c96839e](https://github.com/charmbracelet/soft-serve/commit/c96839ec46aea33b5fa6689a654c2d59f4b90d95). You can try it using https://github.com/charmbracelet/soft-serve/pull/369. If you want, you could help test this new `browse` feature that lets you browse repositories locally `soft browse [repo path]`. I will update the PR body description to include a TODO list if you want to help implement new features :)

**Comment by emilaleksanteri** [comment]
@aymanbagabas oh right sounds good! Yeah would love to help with some of this stuff :)

**Comment by emilaleksanteri** [comment]
@aymanbagabas  mind if I take the remote branches TODO if you haven't started that yet?
