### ISSUE TITLE
LFS push hangs

### ISSUE THREAD

**Issue by wallace11** [charmbracelet/soft-serve#385]
**Describe the bug**
Trying to push my existing LFS project works but hangs just at the end.

Client side: (after uploading, it just stays like that forever)
```bash
$ git push
Uploading LFS objects: 100% (114/114), 248 MB | 12 MB/s 
```

Server side: (`hash` is an actual hash...)
```log
...
git  | 2023-09-18 22:09:10 INFO lfs-transfer: Object name: /soft-serve/lfs/7/incomplete/hash
git  | 2023-09-18 22:09:10 INFO lfs-transfer: Object name: /soft-serve/lfs/7/incomplete/hash
...
```

**To Reproduce**
1. Clone an existing git lfs repo
2. `git lfs fetch --all`
3. `git remote remove origin`
4. `git remote add origin ssh://...`
5. `git push -u origin BRANCH`
6. starts to upload and hangs

**Expected behavior**
Push would end at some point?

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Linux
 - Terminal kitty
 - Version 0.29.2
 - git version 2.42.0

**Additional context**
N/A

**Comment by aymanbagabas** [comment]
@wallace11 could you try this with `lfs.ssh_enabled` disabled in your server settings?

**Comment by wallace11** [comment]
> @wallace11 could you try this with `lfs.ssh_enabled` disabled in your server settings?

Thanks for the quick reply.
I can only access my server via ssh, but I tried to give this a shot anyway and obviously run into an issue:
```bash
batch request: missing protocol: "/repo.git/info/lfs"                                                                                                                     
batch request: missing protocol: "/repo.git/info/lfs"
error: failed to push some refs to 'ssh://...'
Error: something went wrong
```

**Comment by aymanbagabas** [comment]
@wallace11 you would need to expose your soft-serve http server test this

**Comment by wallace11** [comment]
It took me some time to figure out HTTP encryption, but I finally managed to successfully clone a private repo.
I then edited the remote to be `https://token@url/repo.git` and tried to push. Then I got:
```bash
Uploading LFS objects:   0% (0/114), 0 B | 0 B/s, done.
missing protocol: "/repo.git/info/lfs/objects/basic/hash"
missing protocol: "/repo.git/info/lfs/objects/basic/hash"
...
error: failed to push some refs to 'https://url/repo.git'
```

**Comment by wallace11** [comment]
Okay, fiddling with it again now I figured out my mistake from last night - I did not set an http public url. 
After changing that and restarting the container, I managed to push the entire repo without an issue.

This narrows down the issue to SSH only :)

**Comment by aymanbagabas** [comment]
Now we need to figure out if it's a `git-lfs` related issue or not. What `git lfs version` are you running?

**Comment by wallace11** [comment]
```
git-lfs/3.3.0 (GitHub; linux amd64; go 1.19.4)
```

**Comment by wallace11** [comment]
I've compiled git-lfs from source:
```
git-lfs/3.4.0 (GitHub; linux amd64; go 1.21.1)
```

I repeated the test from before:
1. Remove the repo from soft-serve (as it was successfully created using https)
2. Enable ssh in server
3. Set the git remote to `ssh://.../repo` on the client

My finding: the issue persists with this version as well.

---

Interestingly enough, trying to push using the http remote that I used before (but this time with `lfs.ssh_enabled = true`) worked but the LFS routine was skipped.
I confirmed that by cloning the repo again and running `git lfs fetch --all` which resulted in an error.

**Comment by lovepreetjassal** [comment]
Hello, I am also having the same problem.

`Uploading LFS objects: 100% (1/1), 444 B | 0 B/s`

Let me know how I can help debug this.

**Comment by aymanbagabas** [comment]
This is probably related to https://github.com/git-lfs/git-lfs/issues/5535 and https://github.com/git-lfs/git-lfs/pull/5537. Could you try the latest git-lfs build from master?

**Comment by KyleFromKitware** [comment]
> This is probably related to [git-lfs/git-lfs#5535](https://github.com/git-lfs/git-lfs/issues/5535) and [git-lfs/git-lfs#5537](https://github.com/git-lfs/git-lfs/pull/5537). Could you try the latest git-lfs build from master?

I agree, this looks a lot like the issue I ran into that prompted git-lfs/git-lfs#5537. Please try building the latest `main` of git-lfs.

**Comment by KyleFromKitware** [comment]
As a workaround, you may also want to try setting `lfs.ssh.automultiplex` to `false`.

**Comment by aymanbagabas** [comment]
LFS SSH is now disabled by default, you can enable it in your `config.yaml`. Closing
