### ISSUE TITLE
Error: user not found

### ISSUE THREAD

**Issue by Jack-Chronicle** [charmbracelet/soft-serve#387]
**Describe the bug**
After setting up a clean install, I tried to add a user, but was given an unauthorized error
Went to check the user's, and was given an error that there were no users found

**To Reproduce**
1. ssh -p (port) localhost info
2. Get error 

**Expected behavior**
See list of users, or just default admin user

**Environment (please complete the following information):**
 - OS: [Debian 12]
 - Terminal [gnome-terminal]
 - Version [v0.6.1]

**Comment by taigrr** [comment]
Can you double check the ssh command? It doesn't look quite right

**Comment by Jack-Chronicle** [comment]
Sorry, port didn't show up with how I had formatted it

**Comment by taigrr** [comment]
This is not a bug, you might have missed a section of the README:
> When you run Soft Serve for the first time, make sure you have the SOFT_SERVE_INITIAL_ADMIN_KEYS environment variable is set to your ssh authorized key. Any added key to this variable will be treated as admin with full privileges.

The error message you posted is expected behavior when the environment variable is unset

**Comment by Jack-Chronicle** [comment]
I'm setting it up with docker compose, and forgot to add that as a variable
Got it set up and working now

**Comment by taigrr** [comment]
@aymanbagabas closeable
