### ISSUE TITLE
ControlMaster breaks  commands

### ISSUE THREAD

**Issue by denzuko** [charmbracelet/soft-serve#426]
**Describe the bug**
When using `ControlMaster` in `$HOME/.ssh/config`, soft serve only displays the menu and does not log anything from the client connection. Menu navigation does work but cannot execute `info`, `repo create ..`, or like commands.

**To Reproduce**
1. setup a fresh soft serve server with `go install ...`
2. add the following to one's ~/.ssh/config:
```
Host softserve
        User admin
        Hostname localhost   # issue encountered both with & without this and the above. Adding for ease of testing (Host ... is arbitrary too)
       Port 23231
       ControlMaster     auto
       ControlPath       ~/.ssh/control-%C
       ControlPersist    yes
```
3. ssh softserve info

**Expected behavior**
Not to see menu view and that documented behavior works as intended

**Environment (please complete the following information):**
 - OS: Alpine Linux 3.18.2
 - OpenSSH_9.3p2, OpenSSL 3.1.2 1 Aug 2023
 - Version v0.7.1

**Comment by aymanbagabas** [comment]
Hi @denzuko, Soft Serve doesn't support SSH ControlMaster. Soft Serve uses Golang SSH server which doesn't support ControlMaster, there is this open issue regarding adding support to ControlMaster in Golang crypto/ssh https://github.com/golang/go/issues/32958
