### ISSUE TITLE
Markdown rendering of about page is broken after 0.7

### ISSUE THREAD

**Issue by orhun** [charmbracelet/soft-serve#435]
**Describe the bug**

I have a `soft-serve` server at `git.orhun.dev`.

With `image: charmcli/soft-serve:v0.6`:

![image](https://github.com/charmbracelet/soft-serve/assets/24392180/c0d78c22-a671-4542-a98a-cdbdf7320f95)

With `image: charmcli/soft-serve:v0.7`:

![image](https://github.com/charmbracelet/soft-serve/assets/24392180/48bcc6bc-8c70-4bd7-8692-4550ee701b1d)

With `image: charmcli/soft-serve:latest`:

![image](https://github.com/charmbracelet/soft-serve/assets/24392180/6a0be3b6-d57f-4462-8a77-57e5f78b0c4c)

**To Reproduce**
Use the latest version.

**Expected behavior**
Correct markdown rendering.

**Additional context**
Thanks for `soft-serve`! 💖 

I would like to contribute the fix if I can find it out.

**Comment by aymanbagabas** [comment]
Thanks for reporting this @orhun! This will be fixed in the next patch release 🙂
