### ISSUE TITLE
connected refused when running soft-serve as a container

### ISSUE THREAD

**Issue by xuwhao** [charmbracelet/soft-serve#44]
## Description

I try to use docker to run soft-serve. The container create successfully, and I am sure  environment variables are set correctly.   
Then I try to connect to the TUI via ssh, something very bad happened.

## What I expect to see

TUI views.

## What actually happened

Connection refused.

![image](https://user-images.githubusercontent.com/46437721/145722115-e6c23098-655b-4b94-929c-8be8380fa219.png)

### OS

Ubuntu 20.04 LTS.

### OS environment variables

![image](https://user-images.githubusercontent.com/46437721/145722190-0abae048-67fa-44d1-a965-a05d0ff41158.png)

### docker-compose.yml

```docker
---
version: "3.1"
services:
  soft-serve:
    image: charmcli/soft-serve:latest
    container_name: soft-serve
    volumes:
      - ~/soft-serve/data:/soft-serve
    ports:
      - 27017:23231
    restart: unless-stopped
    environment:
      - SOFT_SERVE_INITIAL_ADMIN_KEY=<My public key>
```

## Others

btw, Charm is so cooooooool!

**Comment by xuwhao** [comment]
set all the five env variables,  it works.

**Comment by muesli** [comment]
Thank you for the feedback!
