### ISSUE TITLE
public_url/clone address missing

### ISSUE THREAD

**Issue by omenius** [charmbracelet/soft-serve#440]
**Describe the bug**
The cloning url (public_url) is missing from every view and the 'c' (copy) command is copying nothing.

**To Reproduce**
On my machine, steps to reproduce:
1. Install soft-serve 0.7.3 arm64 deb from repo.charm.sh using apt
2. Add SOFT_SERVE_INITIAL_ADMIN_KEYS to /etc/soft-serve.conf (this is probably irrelevant step)
4. Enable and start service using systemd with provided /lib/systemd/system/soft-serve.service file
5. Push some repo(s) in
6. ssh into the soft-serve TUI, with or without the admin key

**Screenshots**
![issue](https://github.com/charmbracelet/soft-serve/assets/20633778/3952e301-adf8-4f83-831d-f25cb193ea9d)

**Environment (please complete the following information):**
 - OS: Armbian (23.11.1)
 - Terminal alacritty/tty
 - Version 0.7.3

**Additional information**
It doesn't seem to matter which value public_url is set to. I tried with internal ip, external ip, localhost and 'git.example.com'. I've changed them all (ssh, git, http) with no results. I also have external port 22 routed to internal port 23231 with iptables, but surely that is not a part of the problem. Problem is present also when using ssh from localhost (using port 23231).

**Systemctl output**
```
Dec 07 16:11:04 odroidc2 systemd[1]: Started soft-serve.service - Soft Serve git server 🍦.
Dec 07 16:11:04 odroidc2 soft[8605]: 2023-12-07 16:11:04 server: Starting Git daemon addr=:9418
Dec 07 16:11:04 odroidc2 soft[8605]: 2023-12-07 16:11:04 server: Starting HTTP server addr=:23232
Dec 07 16:11:04 odroidc2 soft[8605]: 2023-12-07 16:11:04 server: Starting Stats server addr=localhost:23233
Dec 07 16:11:04 odroidc2 soft[8605]: 2023-12-07 16:11:04 server: Starting SSH server addr=:23231
```

Did I miss something?

**Comment by aymanbagabas** [comment]
Hi @omenius, thanks for reporting this. It was fixed in 0a38578ae6ad and is now released in [v0.7.4](https://github.com/charmbracelet/soft-serve/releases/tag/v0.7.4)
