### ISSUE TITLE
unicode path in tui

### ISSUE THREAD

**Issue by daviehh** [charmbracelet/soft-serve#457]
**Is your feature request related to a problem? Please describe.**
In the "Files" view in the TUI, if the path is non-ascii, it shows the number like `\343\201...` 

**Describe the solution you'd like**
Show unicode file/commit?

Thanks!

<img width="251" alt="Screenshot 2024-01-04 at 9 49 32 PM" src="https://github.com/charmbracelet/soft-serve/assets/25255906/1d96f73a-3698-4471-9a74-361d19273c1a">

**Comment by jtams** [comment]
I was able to reproduce the problem on MacOS/iTerm. The solution that worked for me was setting [core.quotePath](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corequotePath) to false:

`git config --global core.quotePath false`
