### ISSUE TITLE
CI/CD features

### ISSUE THREAD

**Issue by 4thel00z** [charmbracelet/soft-serve#49]
Hello,
I like the idea of the project. Do you think it would be a good idea to add CI/CD features ?

Something like `github` actions living in `.soft/workflows` or maybe supporting the format of `gitlab-ci.yml` - one could reuse the gitlab workers, since they are a standalone project.

Cheers

**Comment by 4thel00z** [comment]
@meowgorithm ping

**Comment by romangraef** [comment]
Even just having webhooks would be pretty nice, in order to use with jenkins or similar.

**Comment by 4thel00z** [comment]
Nice, I can provide some help if you want.

**Comment by toby** [comment]
Thanks! We've got a few other things in the pipeline but will let you know asap. We definitely want this.

**Comment by ebdmuir** [comment]
Can we not just use `post-receive` git hooks? For now at least. That was my initial assumption. Have yet to set it up so I have no idea whether or not I can access them.

**Comment by jshield** [comment]
configuring web hooks and exposing git hooks through a per repo config repo i.e. I can clone <repo>-config and then update the hooks, etc.

don't integrate any particular CI/CD system into soft-serve binary itself instead produce plugins like terraform that can expose a job scheduler for a given CI/CD system that can then use either the git/web hooks to submit a job to the scheduler for dispatch to the workers/agents, perhaps also provide a mechanism to template the per repo config repo from the system config repo.

**Comment by romangraef** [comment]
Are there any updates on this?

**Comment by aymanbagabas** [comment]
You can use [server hooks](https://github.com/charmbracelet/soft-serve#hooks) to implement CI/CD for your Soft Serve server. This is implemented in Soft Serve [v0.5.0](https://github.com/charmbracelet/soft-serve/releases/tag/v0.5.0)
