### ISSUE TITLE
Blocking anon users from accesing server with allow-keyless set to True

### ISSUE THREAD

**Issue by sirdrops** [charmbracelet/soft-serve#524]
**Describe the bug**
After setting allow-keyless to true, and anon-access to no-access I assumed I could still use http/git connection while making unauthorized users unable to access the server over ssh yet I can still access the server,browse and clones repos with anon-user.
Am I misunderstanding how both of those settings work?

**To Reproduce**
Set allow-keyless true
Set anon-access no-access
ssh -p 23231 <server_address> - from anon user

**Expected behavior**
Able to use http/git connections with tokens while disabling anon users from accessing server altogether

Hosted on linux 24.04, soft server installed from repository

**Comment by n1yn** [comment]
I also experience the same issue on my instance

**Comment by aymanbagabas** [comment]
Thank you for reporting this issue @sirdrops & @n1yn! This is now fixed in `main` and will be released in v0.7.7.
