### ISSUE TITLE
Option to change an existing repo's default branch

### ISSUE THREAD

**Issue by whitbur** [charmbracelet/soft-serve#79]
First off, thank you so much for your work on this open source project!

Currently the only way to change the default branch is to ssh directly into the Soft Serve host and manually reassign the HEAD symref via `git symbolic-ref HEAD refs/heads/main`. This isn't a setting that can be set on the client-side and pushed, it must be set server-side. Other git servers like (GitHub, GitLab, Gitea, etc) usually offer a "settings" option in the UI to change this. This is necessary when moving old or misconfigured repos from `master` to `main`, for example.

It would be spiffy if there were a way to change this setting from the TUI, and might fold in nicely with other server-side settings like CI/CD features (#49) in the future.

**Comment by toby** [comment]
This is a good feature request and we should support it. Thanks for filing.
