### ISSUE TITLE
Docs for visible repos in menu possibly misleading

### ISSUE THREAD

**Issue by htaunay** [charmbracelet/soft-serve#80]
In the [configuration file example available in the README](https://github.com/charmbracelet/soft-serve#configuration), there is a comment above the `repo` list item that states:

	# Which repos should appear in the menu?

However, I have noticed that if I push a new repo to soft **without** an entry in the `repo` list configuration it still shows up in the menu, even for non admin users.

In fact, the only way I have found to be possible hide a repo from the menu is with the following steps:

1. Create an entry for a new repo in the config
2. Mark the repo's `private` setting as `true`
3. Create a non-admin user which does **not** have the new repo in its `collab-repos`
4. ssh into soft with said user

Therefore, the documentation stating `Which repos should appear in the menu?` seems misleading, unless I am missing anything. A suggestion for an alternative doc (taking into account I have very little experience with the tool) could be something like:

	# Customization of avaialble repos
	# If a pushed repo is not included here, then it will be public and visible by default

Some extra details:

* The version I'm working with is `Soft Serve v0.1.3 (3aa9bf3)`
* When reproducing the issue my config for `anon-access` was `no-access`, and for `allow-keyless` was `false`

Finally, my sincere thanks to the maintainers for this awesome project :smile:

**Comment by toby** [comment]
Good catch! The comment we have isn't accurate and it works as you describe. We should make it more clear.

**Comment by aymanbagabas** [comment]
This is resolved in [v0.3.3](https://github.com/charmbracelet/soft-serve/releases/tag/v0.3.3). Soft Serve now doesn't show private repositories for unauthorized users.
