### ISSUE TITLE
Config Private Value not honored by TUI menu

### ISSUE THREAD

**Issue by grondinm** [charmbracelet/soft-serve#81]
Hello,

First off I love this project. Just starting to use it and plan on moving all my personal Git repos to it. One thing I'm running into during my initial test setup is that the Private config option does not seem to be honored. I have this in my config

```
repos:
   - name: Welcome
     repo: Welcome
     private: false
     note: "Welcome Page"
   - name: Settings
     repo: config
     private: true
     note: "Configuration and content repo for this server"
```

but when I connect without Auth the Settings repo still shows up in the menu. Am I misunderstanding something? Sorry if I missed something obvious. I'm just connecting locally for now.

**Comment by jackwilsdon** [comment]
Have you set up any users? What's your `anon-access` option set to?
