### ISSUE TITLE
Can't start soft-serve with .ssh in repo

### ISSUE THREAD

**Issue by iveqy** [charmbracelet/soft-serve#99]
Reproduce:
1. Create a new folder: mkdir /srv/repo
2. Go to that folder: cd /srv/repo
3. Run soft: SOFT_SERVE_REPO_PATH=/srv/repo soft

Soft serve will hang and not start, since .ssh will be at repo path and that confuses soft.

**Comment by iveqy** [comment]
The error message is not very helpful and the only reason I found the issue was with strace:
a strace gave some examples: openat(AT_FDCWD, "/srv/repo/.ssh/packed-refs", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

**Comment by aymanbagabas** [comment]
Fixed in the latest release. Closing.
